### ISSUE TITLE
"civil code" is divided in ly but not moj

### ISSUE THREAD

**Issue by kong0107** [g0v/laweasyread-data#4]
"civil code"（民法） is a single statute (with a unique PCode=B0000001) in law.moj.gov.tw , but not so in lis.ly.gov.tw .

For Legislative Yuan（立法院）, each "division" （編） in civil code is treated as a single statute. Therefore, each division has its own ID (04507, 04509, 04511, 04513, 04515) and amended data/documents.

**Comment by czchen** [comment]
Where can we get the mapping table between lyID and PCode?

**Comment by kong0107** [comment]
I don't know whether there exists a mapping table.

But we can craw names from http://lis.ly.gov.tw/lghtml/lawstat/version2/ by fetching each folder's last file with their lyID.
And we can know the pcode-name mapping by crawing the links in the left-hand list of http://law.moj.gov.tw/LawClass/LawClassListN.aspx or http://law.moj.gov.tw/LawClass/LawClassList.aspx .

(Sorry, I'm still in work....cannot implement the parser in these days...orz)

**Comment by czchen** [comment]
I wrote a script to get PCode and name mapping in 425e63ded53dc27a48c6796c4ce43c5345e0b31f.

**Comment by czchen** [comment]
There are several statutes that do not have PCode, so we cannot use PCode as index.

And I found [this statute (lyID: 90077)](http://lis.ly.gov.tw/lghtml/lawstat/version2/90077/9007736061200.htm) does not have name.

**Comment by kong0107** [comment]
For lyID 90077, see issue #6 
About those without PCode, can you give me some examples or links?

For future works, I think it is still necessary to have our own ID for each regulation -- if we wanna include other regulations not found in law.moj.gov.tw, such as:
- [憲法法庭旁聽注意事項](http://jirs.judicial.gov.tw/FLAW/FLAWDAT01.asp?lsid=FL000877), whose competent authority (主管機關) is Judicial Yuan (司法院)
- [臺北市都市更新自治條例](http://www.laws.taipei.gov.tw/taipei/lawsystem/showmaster01.jsp?LawID=P13D1001-20111110&RealID=13-04-1001), which is maintained by Taipei City.

Since there's no existing system handling all regulations, maybe ours may be the first one, and therefore we shall have our own unique index for each regulation. 
Of course, in the short term, we shall focus only on lyID or PCode, since they have the most frequently mentioned regulations.

**Comment by czchen** [comment]
See [here](https://gist.github.com/czchen/5325270) for statute without PCode. I just use exact string match to find PCode, so if the statute name are different between moj and ly, it will be listed.

**Comment by kong0107** [comment]
Oops.. It seems like that old laws are not embodied in moj. [Here](http://law.moj.gov.tw/Qanda.aspx) it says that "收錄90年4月以後發布之命令位階歷史法規", which means regulations updated before 2001 may not be there.

**Comment by czchen** [comment]
I put the PCode into statute.json (19a91264c3273f35cbd78626abab316221142c96) and add special handling for Civil Code (d9bc9099d6054d6aeeb64a2f94ba82cbb6b5928e). I think it is good enough for now.
