### ISSUE TITLE
Handle nameless statute properly

### ISSUE THREAD

**Issue by czchen** [g0v/laweasyread-data#6]
[This statute (lyID: 90077)](http://lis.ly.gov.tw/lghtml/lawstat/version2/90077/9007736061200.htm) does not have name. We need to handle it.

**Comment by kong0107** [comment]
For lyID 90077, its name is "外交部特派員公署組織條例" (known by Googling some of its content)
But I haven't found a way to fetch it through the ly website... 
Since [it](https://gist.github.com/czchen/5325270) seems to be the only case, maybe we can just treat it as a special case?

**Comment by czchen** [comment]
We can handle this as a special case.

Is there any way to report this to the Legislative Yuan?

**Comment by clkao** [comment]
@czchen put the list of entries without name to this hackpad?  https://hackpad.com/g0vccw-NRjYLlK4Umm
our friends @ ccw might pick it up when they talk to some real people next time.

**Comment by czchen** [comment]
Hi @clkao , I put the link to hackpad.
