### ISSUE TITLE
Two instances as "Presidential Election and Recall Act" in both ly and moj system

### ISSUE THREAD

**Issue by kong0107** [g0v/laweasyread-data#7]
For "Presidential and Vice Presidential Election and Recall Act" (總統副總統選舉罷免法), there are two IDs and different names in ly and moj sites. (I don't know the difference of their contents yet.)

In ly:
- [04311](http://lis.ly.gov.tw/lgcgi/lglaw?@231:1804289383:f:NO%3DC704311*%20OR%20NO%3DC004311%20OR%20NO%3DC104311$$4$$$NO): "總統副總統選舉罷免法（民國36年）"
- [04318](http://lis.ly.gov.tw/lgcgi/lglaw?@231:1804289383:f:NO%3DC704318*%20OR%20NO%3DC004318%20OR%20NO%3DC104318$$4$$$NO): "總統副總統選舉罷免法"

In moj:
- [A0020001](http://law.moj.gov.tw/LawClass/LawHistory.aspx?PCode=A0020001): "總統副總統選舉罷免法（舊 36.03.31 制定）"
- [D0020053](http://law.moj.gov.tw/LawClass/LawHistory.aspx?PCode=D0020053): "總統副總統選舉罷免法（新 84.08.09 制定）"

In @czchen['s gist](https://gist.github.com/czchen/5325270), name of lyID 04311 lack "（民國36年）" as postfix.

**Comment by czchen** [comment]
Judge by their contents, [lyID 04311](https://github.com/g0v/laweasyread-data/blob/fd20079d85becac948171af76dd7098be3609bfb/rawdata/utf8_lawstat/version2/04311/0431143031200.html) and [lyID 04318](https://github.com/g0v/laweasyread-data/blob/fd20079d85becac948171af76dd7098be3609bfb/rawdata/utf8_lawstat/version2/04318/0431898051200.html) are different laws with the same name. I think we need to treat them as exception.
